server.port=${PORT:8080}

# Database - Render PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8907pgjo6nc73dckc80-a/ecommerce_db_znjv?sslmode=require
spring.datasource.username=ecommerce_db_znjv_user
spring.datasource.password=S2fRJxoEsN5wQuBnc6QJxgSUqEppDzjS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration=86400000

# Stripe
stripe.api.key=${STRIPE_API_KEY:sk_test_YOUR_KEY}